apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quake-kube.fullname" . }}-server-config
  labels:
    {{- include "quake-kube.labels" . | nindent 4 }}
data:
  config.yaml: |
    fragLimit: {{ .Values.fragLimit }}
    timeLimit: {{ .Values.timeLimit }}
    bot:
      minPlayers: {{ .Values.bot.minPlayers }}
    game:
      motd: "Welcome to Quake Kube"
      type: {{ .Values.game.type }}
      forceRespawn: {{ .Values.game.forceRespawn }}
      inactivity: {{ .Values.game.inactivity }}
      quadFactor: {{ .Values.game.quadFactor }}
      weaponRespawn: {{ .Values.game.weaponRespawn }}
    server:
      hostname: "quakekube"
      maxClients: {{ .Values.game.maxClients }}
      password: {{ .Values.server.password }}
    commands:
      {{- toYaml .Values.commands | nindent 6 }}
    maps:
      {{- toYaml .Values.maps | nindent 6 }}
